### ISSUE TITLE
Document attributeOverride tool.

### ISSUE THREAD

**Issue by williamspatrick** [open-power/hostboot#11]
Attribute override text file format is not documented in a publically available document.  Please create a readme under Hostboot and/or open-power/docs.

**Comment by aalugore** [comment]
I have added a README file to the top level of open-power/hostboot. Someone please review to ensure it has the information we want.

**Comment by aalugore** [comment]
Second draft is up

**Comment by aalugore** [comment]
Third draft

**Comment by williamspatrick** [comment]
We should leave issue open until code shows up.  Please put 'Resolves open-power/hostboot#11' in your commit message and github will automatically close this issue once the commit has been merged and mirrored to github.

**Comment by aalugore** [comment]
What code? isnt this issue just for the README?

**Comment by williamspatrick** [comment]
You said you had a commit you were working on.  This is what I meant.  I guess if it is just documentation there is no code but there is still a commit.

**Comment by williamspatrick** [comment]
I see the confusion.  You modified hostboot directly in github, which is not allowed.  You need to make a commit in gerrit for review.
