### ISSUE TITLE
Commit 3da96b leaves op-build tree dirty

### ISSUE THREAD

**Issue by wghoffa** [open-power/hostboot#111]
Commit 3da96b958d3b248737febeb85951a0e446787d07 is causing a temporary file to be created which is leaving the op-build tree in a dirty state. At a minimum we need to move the temporary file into an appropriate build/staging directory as right now it is falling in op-build/buildroot/.

**Comment by sgupta2m** [comment]
@rajadas2 can you please fix it.

**Comment by rajadas2** [comment]
@wghoffa after building the op-build,
"op-build witherspoon-sequoia_defconfig && op-build hostboot-rebuild openpower-pnor-rebuild"

 i don't see anything in "git status"
-bash-4.1$ pwd
/esw/san5/rajadas2/open-power/witherspoon/op-build
-bash-4.1$ git status
# On branch master
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#   (commit or discard the untracked or modified content in submodules)
#
#	modified:   buildroot (untracked content)
#
no changes added to commit (use "git add" and/or "git commit -a")

Is this the file you are referring to, when you mention a temporary file created is leaving the op-build tree in a dirty state
"buildroot/merged_target_types.xml"

**Comment by wghoffa** [comment]
@rajadas2 - Is this before or after your fix?

Yes, this was the temporary file we saw: "buildroot/merged_target_types.xml"

**Comment by rajadas2** [comment]
@wghoffa i have pushed a patch to remove the temp file
http://ralgit01.raleigh.ibm.com/gerrit1/44942

**Comment by stewart-ibm** [comment]
Fixed in  b80767ab3dbff04b481cd2855d8af3a0c323f6c5
