### ISSUE TITLE
attributeOverride creates file aligned wrong for ECC.

### ISSUE THREAD

**Issue by williamspatrick** [open-power/hostboot#12]
If you create an attribute override file with 1 entry the resulting file has ECC added but is only 4096 bytes.  When you flash this into the ATTR_TMP partition, it causes a PNOR UE to be reported.  When the ECC option is enabled we should be aligning to 4608 bytes to compensate for the ECC bytes.  (4096 * 9 / 8).

**Comment by aalugore** [comment]
the fix has been pushed up to gerrit for review
