### ISSUE TITLE
Stratton (7063-CR1) ipmitool to get NTP configuration information

### ISSUE THREAD

**Issue by karthikeyankp** [open-power/hostboot#165]
In  Stratton (7063-CR1) when BMC is configured with NTP, then HMC will not be able to modify the system time, as time will be always synched with BMC's NTP configuration. 

In this case, we want to show the HMC user a message saying he cannot change the time as NTP is configured in BMC. 

As you know, we query the BMC information through ipmitool command. can you help us get the right ipmitool command to check if BMC in Stratton (7063-CR1) is configured with NTP or not ?
Earlier we got the below command from FSP team. but we cannot use this command, as HMC will not have BMC ip information.

ipmitool -H <BMC>  -U ADMIN -P admin raw 0x32 0xa7

Look at fist byte of the output:
01 --> NTP is configured
00 --> NTP is not configured 

Can you help to get ipmitool command without -H option, basically without passing BMC ip information.

Thanks & Regards
Karthik

**Comment by dcrowell77** [comment]
You need to contact Supermicro for issues on the BMC.  Hostboot is not involved in any way.  https://github.com/open-power/supermicro-openpower/issues/ if you have access
