### ISSUE TITLE
PnorUtils.pm creates unnecessary file

### ISSUE THREAD

**Issue by artemsen** [open-power/hostboot#188]
Package PnorUtils.pm provides function `loadPnorLayout` that called from different places.
The commit 845fb4492dce998d95a0ab2542b05c866c0f5edc modifies that function and now every call to `loadPnorLoyout` creates a temporary file `*WithOffsets.xml` in current directory:
https://github.com/open-power/hostboot/blob/845fb4492dce998d95a0ab2542b05c866c0f5edc/src/build/buildpnor/PnorUtils.pm#L258

It's not a big problem, but after building we always have DIRTY flag reported by git, because directory `op-build/buildroot` now contains excess file created by buildpnor.pl->PnorUtils.pm.

**Comment by lpfluisfer** [comment]
I'm taking a look at this. Ultimately we wanted those *WithOffsets.xml files to end up in: 
_<op-build_repo>/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch/defaultPnorLayout_64WithOffsets.xml_

But it may be that the script is being run from the Buildroot level as well.

**Comment by artemsen** [comment]
It actually ends up there, when PnorUtils.pm is called by [genPnorImages.pl](https://github.com/open-power/hostboot/blob/845fb4492dce998d95a0ab2542b05c866c0f5edc/src/build/buildpnor/genPnorImages.pl#L389).
But the second call from [buildpnor.pl](https://github.com/open-power/hostboot/blob/845fb4492dce998d95a0ab2542b05c866c0f5edc/src/build/buildpnor/buildpnor.pl#L115) creates the file in default directory, which is [op-build/buildroot](https://github.com/open-power/op-build/blob/e002a0fb45d6bf50ed8d8a270a9110604a8afdfd/op-build-env#L18).

We can set CWD before executing buildpnor.pl, like it does `make` for genPnorImages.pl.
But it looks ugly for me.
May be a function named `load` shouldn't save a file? :)

**Comment by dcrowell77** [comment]
See https://github.com/open-power/pnor/pull/130 for a possible fix

**Comment by artemsen** [comment]
Thanks!
Works fine in the latest master.
