### ISSUE TITLE
NX Nest AES/SHA accelerators support on PowerNV POWER9 Sforza (and others)

### ISSUE THREAD

**Issue by leo-lb** [open-power/hostboot#196]
In the POWER9 Sforza processor user manual: https://www-355.ibm.com/systems/power/openpower/posting.xhtml?postingId=FC2A3168C5821FA78525803D00719802

There is:

![Screenshot_2021-02-27 POWER9 Processor User's Manual - POWER9_um_OpenPOWER_v21_10OCT2019_pub pdf](https://user-images.githubusercontent.com/44934014/109396718-38e8b580-7933-11eb-9826-4d85612c1aab.png)

Which documents AES and SHA accelerators, however I can't find clues about support in Hostboot, I heard it needs something here.

AES NX accelerators are unsupported on PowerNV in the Linux kernel as well: https://github.com/torvalds/linux/blob/master/drivers/crypto/nx/Kconfig#L3

I wonder, how can this situation be sorted? Since internal documentation to the POWER9 Sforza processor is not available, I don't know what to do to add support here.

I am asking because it is especially relevant for luks/dm-crypt performance, I recently bought PCI-e 4.0 SSDs which is my first time actually making use of the PCI-e 4.0 slots and the Samsung 980 Pro SSDs are rated for 7000MB/s read and 5100MB/s write speeds but luks/dm-crypt can only do ~2500MB/s read/write at maximum in any algorithm (aes-xts fastest currently with encryption vector instructions).

```
$ cryptsetup benchmark
# Tests are approximate using memory only (no storage IO).
PBKDF2-sha1       781353 iterations per second for 256-bit key
PBKDF2-sha256    1201117 iterations per second for 256-bit key
PBKDF2-sha512    1061311 iterations per second for 256-bit key
PBKDF2-ripemd160  611771 iterations per second for 256-bit key
PBKDF2-whirlpool  332248 iterations per second for 256-bit key
argon2i       4 iterations, 1048576 memory, 4 parallel threads (CPUs) for 256-bit key (requested 2000 ms time)
argon2id      4 iterations, 1048576 memory, 4 parallel threads (CPUs) for 256-bit key (requested 2000 ms time)
#     Algorithm |       Key |      Encryption |      Decryption
        aes-cbc        128b       785.7 MiB/s      2961.5 MiB/s
    serpent-cbc        128b        60.1 MiB/s        72.8 MiB/s
    twofish-cbc        128b       122.9 MiB/s       126.7 MiB/s
        aes-cbc        256b       621.3 MiB/s      2427.3 MiB/s
    serpent-cbc        256b        59.0 MiB/s        73.4 MiB/s
    twofish-cbc        256b       120.4 MiB/s       126.9 MiB/s
        aes-xts        256b      2489.2 MiB/s      2577.5 MiB/s
    serpent-xts        256b        61.4 MiB/s        75.5 MiB/s
    twofish-xts        256b       125.1 MiB/s       132.0 MiB/s
        aes-xts        512b      2158.8 MiB/s      2129.4 MiB/s
    serpent-xts        512b        62.7 MiB/s        75.3 MiB/s
    twofish-xts        512b       134.0 MiB/s       132.5 MiB/s
```

Currently it uses the second one here:

```
$ grep -A 11 'xts(aes)' /proc/crypto
name         : xts(aes)
driver       : xts(ecb(aes-generic))
module       : kernel
priority     : 100
refcnt       : 7
selftest     : passed
internal     : no
type         : skcipher
async        : no
blocksize    : 16
min keysize  : 32
max keysize  : 64
--
name         : xts(aes)
driver       : p8_aes_xts
module       : vmx_crypto
priority     : 2000
refcnt       : 7
selftest     : passed
internal     : no
type         : skcipher
async        : no
blocksize    : 16
min keysize  : 32
max keysize  : 64
```

This is not with NX accelerators but AES acceleration instructions (vcipher, vcipherlast) implemented in assembly AFAICT.

See:
- https://www.ibm.com/developerworks/library/se-power8-in-core-cryptography/index.html
- https://github.com/torvalds/linux/blob/master/drivers/crypto/vmx/aesp8-ppc.pl

I use Linux kernel longterm 5.10.19 with Hostboot as shipped by RaptorCS for the Talos II here: https://git.raptorcs.com/git/talos-hostboot/log/?id=a2ddbf3150e2c02ccc904b25d6650c9932a8a841

Thank you

**Comment by dcrowell77** [comment]
Hostboot doesn't take advantage of any of these accelerators.  They are used by code running on top (opal, phyp, linux, whatever).  All of the hardware should be enabled during the boot by default, though there may be some configuration required by the kernel code that ends up using it.

I think a better place for this discussion would be in the opal mailing list.  There should be opal/linux usage somewhere you can use.

**Comment by klauskiwi** [comment]
yes, let's move this to the mailing-list. I believe Haren Myneni was working on this, I can make sure that he is aware of the discussion.

**Comment by leo-lb** [comment]
@dcrowell77 @klauskiwi 

Thanks, what is the address for that mailing list exactly? Some searches don't show an obvious answer.

I know that Hostboot doesnt use these itself but I don't know from where I heard a while ago there was some support code needed in Hostboot before the accelerator was working, hence why I asked here.

**Comment by klauskiwi** [comment]
> 
> 
> @dcrowell77 @klauskiwi
> 
> Thanks, what is the address for that mailing list exactly? Some searches don't show an obvious answer.
> 
https://lists.ozlabs.org/listinfo/openpower-firmware and https://lists.ozlabs.org/listinfo/skiboot are the two main mailing-lists we use
