### ISSUE TITLE
git-describe invocation during op-build.

### ISSUE THREAD

**Issue by williamspatrick** [open-power/hostboot#2]
When doing an op-build, the Hostboot makefile still attempts to run 'git-describe' to determine the current tag to insert into the image as a version.  We need to eliminate this invocation when doing an op-build and pick another sane description based on package variables.  Jeremy did something similar for skiboot (see the openpower/buildroot commit).

**Comment by scprek** [comment]
This should hopefully be resolved with https://github.com/open-power/op-build/pull/58

**Comment by scprek** [comment]
Resolved with

open-power/openpower-pnor@3748ff041448a3909d5ffc5e62befcfcb597c0c1
open-power/op-build@5f8790836fc6fef003988133993a3dcbe565f456

enabled by 
a624fc23909fe907c7c6d3aa3488fa1510484ad3

**Comment by scprek** [comment]
Should be resolved with

open-power/hostboot@a6fa07dacc102c62067e20f69a4c956ac6d1f625
open-power/openpower-pnor@3748ff041448a3909d5ffc5e62befcfcb597c0c1
open-power/op-build@5f8790836fc6fef003988133993a3dcbe565f456

enabled by 
open-power/op-build@a624fc23909fe907c7c6d3aa3488fa1510484ad3
