### ISSUE TITLE
Is the parameter "ATTR_MEM_MRW_IS_PLANAR" TRUE for any platform at present

### ISSUE THREAD

**Issue by Grubby0624** [open-power/hostboot#216]
https://github.com/open-power/hostboot/blob/76013fa56aa7072a7e076d43b5e1fb6b460d88f0/src/import/chips/p10/procedures/hwp/memory/p10_mss_eff_config.C#L71

Is the MRW parameter in the machine-xml database of that platform TRUE

**Comment by dcrowell77** [comment]
No, that value is not set for any current platforms.
