### ISSUE TITLE
what is the Subsequent functions of the entity associationtree?

### ISSUE THREAD

**Issue by wongkq** [open-power/hostboot#217]
Hello:
       Does the entity association tree have any other function besides generating the entity association PDR? If BMC does not have a merge entity association PDR, does the entity association tree of hostboot need to be modified?

**Comment by dcrowell77** [comment]
There are several different (unrelated) uses of the word "association".  Can you point to a specific example so that I understand the context of the question?

**Comment by ibmzach** [comment]
> Does the entity association tree have any other function besides generating the entity association PDR?

Hostboot constructs an entity association tree _in order to_ generate the correct association PDRs, but I'm not sure that answers your question.

> If BMC does not have a merge entity association PDR

What is a "merge entity association PDR"?

> does the entity association tree of hostboot need to be modified?

Hostboot doesn't keep a persistent entity tree, it only builds an ephemeral one to construct the association PDRs for the BMC, and it does this one time during each IPL.

**Comment by wongkq** [comment]
> > If BMC does not have a merge entity association PDR
> 
> What is a "merge entity association PDR"?
> Sorry, I mean hostboot sends entity association PDRs to BMC. If BMC does not merge these PDRs, will hostboot modify its entity association tree?

**Comment by ibmzach** [comment]
Hostboot clears all its PDRs before retrieving them again from the BMC during the PDR exchange. The BMC must merge its entity association PDRs to provide a coherent view of the IDs for the sensors and effecters that are created later. Hostboot doesn't "modify" any entity association tree; it merely correlates the entities that the BMC describes with its own internal hardware information and uses that to create and refer to sensors and effecters for various hardware operations.
