### ISSUE TITLE
Can I map the memory to within 128TB

### ISSUE THREAD

**Issue by Grubby0624** [open-power/hostboot#225]
https://github.com/open-power/hostboot/blob/07e6d7d68f0cce3fdc25848b59baf46aa3dabc5c/src/import/chips/p10/procedures/hwp/nest/p10_mss_eff_grouping.C#L4788

I want to adapt to a lower version kernel on the P10 eBMC system,
The maximum physical memory capacity specified for the kernel is 128TB:
https://github.com/torvalds/linux/blob/c470abd4fde40ea6a0846a2beab642a578c0b8cd/arch/powerpc/include/asm/sparsemem.h#L14
But for 4-proc machines, each group needs to occupy 64TB of memory, so the memory on Proc2/3 cannot be recognized by the kernel. Do we have the means to map the memory on Proc2/3 to within 128TB?
I tried to modify the mapping by modifying the topology ID, but this method only works on iOSCM CPUs. For DCM CPUs, the modification will result in "build smp failed"

**Comment by dcrowell77** [comment]
The 64TB space per topology id is a pretty fundamental piece of the architecture.  I'm not aware of any way to change that.

I would recommend maybe asking over in https://github.com/open-power/skiboot since that team might be more aware of any tricks to get Linux to run.
