### ISSUE TITLE
MVPD code does not account for more than 2 PT keywords in VTOC record with VPD cache enablement

### ISSUE THREAD

**Issue by Frank-yujiang** [open-power/hostboot#23]
Dean has found the root cause and provide the patch as follows:

-- a/src/usr/vpd/ipvpd.C
      +++ b/src/usr/vpd/ipvpd.C
      @@ -1276,7 +1276,7 @@ IpVpdFacade::getRecordListSeeprom
      ( std::list<TocPtRecord> & o_recList,
           offset = le16toh( toc_rec->record_offset ) + 1;  // skip 'large
      resource'

           // Read the PT keyword(s) from the VTOC
      -    for (uint16_t index = 0; index < 2; ++index)
      +    for (uint16_t index = 0; index < 3; ++index)
           {
               pt_len = sizeof(l_buffer);
               err = retrieveKeyword( "PT",

**Comment by williamspatrick** [comment]
Change Ib87300428b00018cea299e1d1962b8d2ccba48fc will fix this.
