### ISSUE TITLE
About Simics

### ISSUE THREAD

**Issue by LoserJL** [open-power/hostboot#231]
Where to get Simics to run hostboot before there is actual hardware?
And Where to get toolchains for "Standalone compile"?

**Comment by dcrowell77** [comment]
You would have to purchase a license from Wind River (https://www.windriver.com/products/simics) and also get Mambo from IBM (https://www.ibm.com/support/pages/power10-functional-simulator-related-resources).

All of the "standalone compile" toolchains should be available as part of gcc.  It is just a cross-compiler.  I would recommend using op-build to compile.  You can then install that toolchain from there to use independently if needed.

**Comment by LoserJL** [comment]
> You would have to purchase a license from Wind River (https://www.windriver.com/products/simics) and also get Mambo from IBM (https://www.ibm.com/support/pages/power10-functional-simulator-related-resources).
> 
> All of the "standalone compile" toolchains should be available as part of gcc. It is just a cross-compiler. I would recommend using op-build to compile. You can then install that toolchain from there to use independently if needed.

Thank you
