### ISSUE TITLE
About istep16.01 "host_activate_boot_core"

### ISSUE THREAD

**Issue by LoserJL** [open-power/hostboot#237]
In hostboot, istep16.01 "host_activate_boot_core", the call_host_activate_boot_core() function is called, 
where the master enters the winkle first, and then wait for a wakeup, I don't understand 
why it is necessary to do this, it looks as if this step is a bit redundant, because the master is 
already running

![image](https://github.com/open-power/hostboot/assets/33047076/7086c0c3-690f-41ae-8fd2-512be8006f5f)

Thanks

**Comment by dcrowell77** [comment]
The initial boot of the master core uses a set of initialization values that are fine for Hostboot to use but are not appropriate for runtime use.  The HOMER image that we customize in step15 will contain the correct runtime inits for the cores/caches.  The secondary cores will pick that up when they get started for the first time in 16.2 but the boot core needs to be sent through STOP11 explicitly to get the new inits.
