### ISSUE TITLE
CDD_ChA_RR_3_2? CDD_ChB_RR_3_2

### ISSUE THREAD

**Issue by Grubby0624** [open-power/hostboot#241]
https://github.com/open-power/hostboot/blob/dd9bd54048915edd0d18f788f95aebcd217152cd/src/import/chips/ocmb/odyssey/procedures/hwp/memory/lib/phy/ody_draminit_utils.H#L3955
Perhaps this line should be io_msg_block.CDD_ChB_RR_3_2=0？

**Comment by stermole** [comment]
good catch @Grubby0624 .  I'll push a fix for it
