### ISSUE TITLE
VPD Caching broken on multiple socket, single CVPD systems (Barreleye)

### ISSUE THREAD

**Issue by sannerd** [open-power/hostboot#29]
Found a bug with the VPD caching:

In fsipres.C, hostboot loops through the all targets and processes VPD cache.  If the CPU or Centaur is not present, it essentially invalidates the PNOR cache for that MVPD/CVPD.  It does this based on FSI HW detect.  If the CPU or Centaur  is present, it will load VPD cache from hardware.      Since there is only 1 physical VPD, if anything is not present, it will invalidate VPD Cache.  This is a bug.  Barreleye hit this bug because it is the only 2 socket system we have with a single VPD chip for all Centaurs.

Here is current (failing) sequence:
1. CPU0/Centaurs -> present -> VPD cache is loaded
2. CPU1/Centaurs -> not present -> VPD cache is invalidated
3. VPD cache is needed but has been invalidated

@dcrowell77 and I brainstormed a couple of solutions -- 

1) Simple hack to reverse order of presence detection from CPU X -> CPU 0.  Not sure about any side effects, but this works because CPU 0 always has to be present 

2) The algorithm is using the FSI presence detect to qualify if VPD is even possible to read.  In this case the singular copy of the VPD is behind the CPU (not the centaur).   Fix would be to update the presence detect  code for centaurs to take into account which target actually has the I2C master that reads the VPD and use that to determine if VPD is reachable. This is likely the proper fix, and what this issue was opened for.

**Comment by williamspatrick** [comment]
Dean, is this resolved?
