### ISSUE TITLE
System always shows "dumping errors" message

### ISSUE THREAD

**Issue by shenki** [open-power/hostboot#34]
I have a Plametto machine and it appears that every time I boot I see this on the console:

```
  2.16642|ERRL|Dumping errors reported prior to registration
```

Why does this happen?

Is there something I can do to fix it?

Thanks!

**Comment by ozbenh** [comment]
On Mon, 2015-09-07 at 20:42 -0700, Joel Stanley wrote:
> I have a Plametto machine and it appears that every time I boot I see
> this on the console:
>   2.16642|ERRL|Dumping errors reported prior to registration
> Why does this happen?
> Is there something I can do to fix it?
Afaik it always did that ... even when there's nothing to dump.

**Comment by dcrowell77** [comment]
Ben is right, that is normal (though I would admit a bit odd.  If there were errors you would see them there.  This seems like something we could remove, need to poke at the code to see if we know about the existence of logs at the point where we print that.

**Comment by ploetzma** [comment]
This would be a good thing for Manali to look into with her error log fix.
We display this trace once the error log handler is enabled - we can just move it into the loop where we find if there are previous error logs.

**Comment by mingfengwuye** [comment]
If errors are dumped here, what does that mean? there is an error in last IPL or now?

**Comment by dcrowell77** [comment]
Any errors logged at this point are leftover from a previous boot.  There 
are situations where we are not able to send the error log out to the BMC 
during the initial error log.  In those cases we save the data to PNOR to 
report on the next boot as extra information.

--
Dan Crowell
Senior Software Engineer - Power Systems Enablement Firmware
IBM Rochester: t/l 553-2987
dcrowell@us.ibm.com

**Comment by shenki** [comment]
We seem to see these messages on every boot, even after doing a clean shutdown. Can we identify what the error is, and check that everything is working as it should?

**Comment by dcrowell77** [comment]
You shouldn't be seeing errors on every boot, just the message "Dumping errors reported prior to registration".  The message alone means nothing.

**Comment by shenki** [comment]
Okay. So it will print "Dumping errors" even when it's not dumping any errors?

**Comment by dcrowell77** [comment]
Yes, I agree that is less than ideal.  It's in our queue of random things to do.

**Comment by mingfengwuye** [comment]
Is there a tool to parsing Errlog in PNOR?

**Comment by dcrowell77** [comment]
> Is there a tool to parsing Errlog in PNOR?
Not at this point.  An error log parser is planned to be released to github at some point.  That tool will be able to take in a flattened binary version of an error log and decode the SRC and other details.

**Comment by mingfengwuye** [comment]
Is there a schedule for that tool?  
Furthermore, now we analyse IPL errors based on BMC's sel. Is that enough and are there any other errors stored in pnor but not sent to BMC?

**Comment by dcrowell77** [comment]
The data in PNOR is only necessary if for some reason we can't send the log out to the BMC.  For most errors you shouldn't need anything except the sel data to replace the bad part.  The full error log is sent to the BMC as an OEM eSEL (0xdf).  That data is useful for more complicated failure analysis.

There is no schedule for release yet.

**Comment by shenki** [comment]
Thanks!
