### ISSUE TITLE
Non-present FRUs are being reported as faulted.

### ISSUE THREAD

**Issue by williamspatrick** [open-power/hostboot#47]
In our IPMI code for OpenBMC, we observed that the hostboot code is setting the fault bit in the FRU sensor for every non-present device.  For DIMM slots that are not populated and for processors with partial-good records, this is probably not the best option.  Can this be changed in the host firmware without breaking other BMC implementations?

See openbmc/openbmc#92.

**Comment by dcrowell77** [comment]
I'm a little confused here.  What is meant by "fault bit" here?  We do send down information for every part, even the non-present ones, but that data should indicate "not present".  We need to send down something to handle the case where the previous boot had detected the part and we need to clear the old status out.  (Adding @wghoffa and @rjknight to the discussion)

**Comment by williamspatrick** [comment]
The ipmi fru status sensor has multiple "offsets" asserted. Non-present and non-functional. Hostboot has a simple translation from hwas bits to ipmi bits. 1 to 1 mapping. Instead we should map non-present (plus non-functional) hwas to just non-present ipmi. 

Patrick

**Comment by rjknight** [comment]
The current mappings are

 States  | IPMI bits
------------ | -------------
NOT_PRESENT | turn off the present bit, turn on the disabled bit
PRESENT | turn on the present bit
FUNCTIONAL | turn off the disabled bit
PRESENT_FUNCTIONAL | turn on the present bit, turn off the disabled bit
PRESENT_NONFUNCTIONAL | turn on the present bit, turn on the disabled bit
NON_FUNCTIONAL  | turn on the disabled bit

Sounds like the suggestion is to update the NOT_PRESENT to turn off the present bit and the disabled bit?

**Comment by williamspatrick** [comment]
Yes, exactly. 

Patrick

**Comment by dcrowell77** [comment]
I'm checking with our service team to see if there are any legacy support issues, so far this request seems reasonable.

**Comment by dcrowell77** [comment]
There were no objections to this change so have at it.
