### ISSUE TITLE
Need to add more FFDC 

### ISSUE THREAD

**Issue by Frank-yujiang** [open-power/hostboot#48]
A PRD error is reported recently from customers recently.  PRD failed because targets that existed on the previous IPL no longer exist during the checkstop analysis. However, not enough FFDC has been recorded for this failure. Has shared the logs with Daniel and Zane.  Maybe need to modify the code to add more FFDC.

**Comment by mzipse** [comment]
Zane, have you looked at the logs?  Any conclusions?  If we need more info, can we suggest gathering any other data?

**Comment by zane131** [comment]
@Frank-yujiang I am just now finding some old issues. Does this issue still need to be resolved?
