### ISSUE TITLE
about  hostboot trace log

### ISSUE THREAD

**Issue by williamspatrick** [open-power/hostboot#65]
@cooktail commented on [Mon Sep 12 2016](https://github.com/open-power/op-build/issues/633)

Hi ,
       When I unset CONSOLE_OUTPUT_TRACE,The hostboot  IPL log is pithily,But I cannot see any trace message.
       Can the hostboot design into SOL print pithily log,And I can check the detail trace message in other places?

**Comment by dcrowell77** [comment]
I had to look up what 'pithily' meant (Pithily definition, brief, forceful, and meaningful in expression; full of vigor, substance, or meaning; terse; forcible).  I think you are saying it doesn't have a lot of information in it?  Can you expand on your suggestion?
