### ISSUE TITLE
processMrw.pl doesn't error on duplicate sensor IDs

### ISSUE THREAD

**Issue by stewart-ibm** [open-power/hostboot#75]
See https://github.com/open-power/serverwiz/issues/29#issuecomment-267120392 for why this should be in processMrw rather than ServerWiz.

We've had at least two places where XML has had duplicate sensor IDs.

OPAL will **warn** on this on boot, with an entry in the log (which will soon be picked up by FWTS as a firmware bug):
```
[   84.176082494,3] DT: dt_attach_root failed, duplicate sensor@9
```

This is caused by having XML that has the duplicate. e.g.:

https://github.com/supermicro/p8dtu-xml/blob/P8DTU_release/p8dtu.xml#L1657
```
<globalSetting>
	<id>/sys-0/boot_count_sensor</id>
	<property>
	<id>IPMI_SENSOR_ID</id>
	<value>0x09</value>
	</property>
</globalSetting>
```
https://github.com/supermicro/p8dtu-xml/blob/P8DTU_release/p8dtu.xml#L5357
```
<globalSetting>
	<id>/sys-0/node-0/motherboard-0/proc_socket-1/module-1/proc/occ-0/occ_active_sensor</id>
	<property>
	<id>INSTANCE_ID</id>
	<value>occ_active_sensor</value>
	</property>
	<property>
	<id>IPMI_SENSOR_ID</id>
	<value>0x09</value>
	</property>
</globalSetting>
```

**NOTE:** identical sensor IDs 0x09

This is something that could be (hopefully) easily enforced in processMrw so that these kind of bugs could be caught much much much earlier.

**Comment by dcrowell77** [comment]
@pragupta - Something to look into while the script is being fixed up for P9.

@spinler - Something to keep in mind on the OpenBMC side of things.
