### ISSUE TITLE
processMrw.pl  doesn't assign FAPI_POS correctly for dimm's

### ISSUE THREAD

**Issue by janssens2** [open-power/hostboot#98]
determining FAPI_POS for a dimm in processMrw.pl is not taking into account the group id.  For example on proc 1 the first dimm FAPI_POS should be 64 and not 16.

**Comment by wghoffa** [comment]
Example output with fix (for Zaius):

[ZAIUS_hb.mrw.zip](https://github.com/open-power/hostboot/files/935712/ZAIUS_hb.mrw.zip)

**Comment by janssens2** [comment]
example output looks good.  Dimm's match what was expected for FAPI_POS now
